# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8671ab7422ae8472f57c9c861db7a68a"
application_url = "https://zu-licence-photographic-earthquake.trycloudflare.com"
embedded = false
name = "Apex-feat-test"
handle = "apex-feat-test"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "checkout-ui-build.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "subscription_contracts/create" ]
  uri = "https://cuz3lhmvci.execute-api.eu-north-1.amazonaws.com/webhook"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,read_cart_transforms,read_checkout_branding_settings,read_content,read_customer_events,read_customer_merge,read_customers,read_delivery_customizations,read_discounts,read_draft_orders,read_files,read_fulfillments,read_gift_cards,read_inventory,read_legal_policies,read_locations,read_marketing_events,read_markets,read_merchant_managed_fulfillment_orders,read_metaobject_definitions,read_metaobjects,read_online_store_navigation,read_online_store_pages,read_order_edits,read_orders,read_own_subscription_contracts,read_payment_customizations,read_payment_terms,read_price_rules,read_privacy_settings,read_product_listings,read_products,read_purchase_options,read_returns,read_script_tags,read_shipping,read_shopify_payments_disputes,read_shopify_payments_payouts,read_store_credit_account_transactions,read_store_credit_accounts,read_themes,read_third_party_fulfillment_orders,read_translations,read_validations,write_assigned_fulfillment_orders,write_cart_transforms,write_checkout_branding_settings,write_content,write_customer_merge,write_customers,write_delivery_customizations,write_discounts,write_draft_orders,write_files,write_fulfillments,write_gift_cards,write_inventory,write_locations,write_marketing_events,write_markets,write_merchant_managed_fulfillment_orders,write_metaobject_definitions,write_metaobjects,write_online_store_navigation,write_order_edits,write_orders,write_own_subscription_contracts,write_payment_customizations,write_payment_terms,write_pixels,write_price_rules,write_privacy_settings,write_products,write_purchase_options,write_returns,write_script_tags,write_shipping,write_store_credit_account_transactions,write_themes,write_third_party_fulfillment_orders,write_validations"

[auth]
redirect_urls = [
  "https://zu-licence-photographic-earthquake.trycloudflare.com/auth/callback",
  "https://zu-licence-photographic-earthquake.trycloudflare.com/auth/shopify/callback",
  "https://zu-licence-photographic-earthquake.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
